### ISSUE TITLE
Starting a Rayo client with the same JID (excluding resource) continues to receive events for which it has no state

### ISSUE THREAD

**Issue by bklang** [rayo/xmpp#17]
Example:

1) I start Adhearsion
2) A caller enters the system and joins a mixer
3) Adhearsion dies (does not clean up state or hang up calls)
4) Adhearsion restarts
5) After restarting Adhearsion receives events from both the call and the mixer

**Comment by benlangfeld** [comment]
Is this dependent on the resource being the same when restarted?

**Comment by bklang** [comment]
it probably is, since this particular app has the resource hard-coded.  I will test.
