### ISSUE TITLE
Input component on mixers

### ISSUE THREAD

**Issue by benlangfeld** [rayo/xmpp#25]

**Comment by benlangfeld** [comment]
From @mpermar:

The semantics are the same as for a regular input component that were executed on a call. The only difference is that any call in the mixer can answer the input command. The complete event will in this case come from the mixer as directed presence to the client. 

The main problem I see with this as it is right now is that in the input semantics there is no information about which call within the mixer did actually was the cause for the input complete. There is an example here https://github.com/rayo/rayo-functional-tests/blob/develop/src/test/java/com/rayo/functional/rayoapi/RayoMixerApiTest.java#L293

**Comment by benlangfeld** [comment]
So only one call in the mixer provides input, or input is the aggregate of signals from all participants?

**Comment by benlangfeld** [comment]
@mpermar: Could you please clarify how this works?

**Comment by mpermar** [comment]
Only one call in the mixer providers input.

**Comment by benlangfeld** [comment]
How does the mixer decide who?

**Comment by mpermar** [comment]
The first call in completing the input wins.

**Comment by benlangfeld** [comment]
So recognisers are started for all calls with separate buffers, and then cleared out once one recogniser matches?

**Comment by mpermar** [comment]
yes

**Comment by benlangfeld** [comment]
@crienzo: I'd love to know your thoughts on this. Does this sound like a sensible behaviour, or should the buffer be shared?

**Comment by crienzo** [comment]
This seems painful to implement (at least in FS) and I can't think of a good use case for this.  Anybody have a good example?

**Comment by bklang** [comment]
Hotword detection in a conference?  Maybe doing it on a conference instead of individual legs to save port licenses?

**Comment by crienzo** [comment]
That seems reasonable.  The client app can always start input on individual legs as needed.

**Comment by crienzo** [comment]
Actually, shared buffer is not possible since you can't tell who made the input and which client to send the result to for processing.

**Comment by benlangfeld** [comment]
You know who started the input component. Events go to that party. Did I miss something?

**Comment by crienzo** [comment]
Nope, that's right.

**Comment by benlangfeld** [comment]
Agreed that shared buffer is the simplest approach, and separate buffers can be started using separate input components.

**Comment by benlangfeld** [comment]
@loopingrage to do further research on the PRISM implementation
