### ISSUE TITLE
Hold/unhold?

### ISSUE THREAD

**Issue by benlangfeld** [rayo/xmpp#30]
How is this different from mute/unmute?

**Comment by benlangfeld** [comment]
@mpermar says "The difference is the media. A call on hold does not receive media. A call muted still does receive media.".

So hold essentially unjoins the call from the media server?

**Comment by mpermar** [comment]
Essentially yes, but I am not sure how it is done at the media server level which is something that would affect licensing.

**Comment by benlangfeld** [comment]
I take it this does not actually remove media, but actually just causes the caller to receive silence? This would suggest that mute (#29) applies only to audio received from the caller? This would make the following conceptual equivalents true:
- `<hold> =~ <start-silence direction="SEND"/>`
- `<mute> =~ <start-silence direction="RECV"/>`

Correct?
