### ISSUE TITLE
TTS/ASR: Is support for these input/output components MAY or MUST for Rayo compatibility?

### ISSUE THREAD

**Issue by bklang** [rayo/xmpp#36]
In section 3 ("Requirements") of the proposed XEP, it mentions:

Speech Synthesis / TTS: In cases where dynamic data must be spoken, a Speech Synthesis engine may be used to play computer generated speech to the caller.

and

Speech Recognition: Enables the phone application to take spoken queues allowing for sophisticated voice-driven menus and directory services.

Are TTS and ASR considered optional for Rayo compliance? If so, we should be more explicit about this, and include examples of error messages where the server is unable to fulfill a TTS or ASR request.

**Comment by benlangfeld** [comment]
I would suggest that TTS/ASR be considered optional, but that Input/Output generally be required for DTMF/audio files. We should probably consider the method of delivery of those audio files also (local vs HTTP etc).

**Comment by benlangfeld** [comment]
ASR = DTMF only
TTS = content-type text/uri-list: http://www.mime-type.net/text/uri-list/
