### ISSUE TITLE
Define which components may execute concurrently?

### ISSUE THREAD

**Issue by bklang** [rayo/xmpp#37]
The current proposed spec mentions that components can and will execute concurrently.  Are there any cases where components may not execute concurrently?  Do we need to document a list of which components are mutually exclusive, and possibly create a special error message for components which may not be executed concurrently?

**Comment by benlangfeld** [comment]
All components should be able to execute concurrently. Any future
components which may not should include an appropriate error
definition.

Regards,
Ben Langfeld

On 16 June 2012 21:43, Ben Klang
reply@reply.github.com
wrote:
