### ISSUE TITLE
Clarify whether call joins require same DCP

### ISSUE THREAD

**Issue by bklang** [rayo/xmpp#38]
The spec mentions that a call may be joined to another call, but does not specify any kind of access control with respect to the calls being joined.

Assume that callA is being controlled by juliet@capulet.lit/instance1 and callB is being controlled by juliet@capulet.lit/instance2.  Since we can assume that the two instances of the same JID are part of the same organization, it follows that there may be a use-case for the two calls to have their media joined.  However, if instance1 requests a join to callB (which is being controlled by instance2) is that permissible?  If not, should the server return an error?  This can be extended to calls that are being controlled by different domains as well.

**Comment by benlangfeld** [comment]
CPs with the same bare JID should be considered to be in the same security zone. Implementations may permit completely different JIDs to be considered to be in the same security zone if they are considered to be attached to the same "app", a la Tropo. That would be implementation specific, but must be allowed by the spec.

Any calls in the same security zone should be joinable, and the same goes for mixers.

**Comment by bklang** [comment]
Allowing calls with different DCPs but in the same zone may lead to unpredictable application behavior.  For example, what does DCP "instance1" do when a call under its control is joined to a call under the control of DCP "instance2"?  Per the current spec, each DCP should get a "joined" event for the call under its control.

If we are going to allow that behavior, I think the spec should be explicit about this possibility and make recommendations ("SHOULD") for what applications do in this case.  Are security zones even a part of this specification yet?

**Comment by benlangfeld** [comment]
Security zones are not part of the spec yet, no.

I think we should allow joins within a SZ but across DCPs, with a recommendation that clients should not do this unless they are confident they know how to deal with it.

**Comment by bklang** [comment]
This works for me assuming we address the issue of security zones and add the recommendation as you describe.  If we do not want to add security zones to this spec, then I think we need to mandate that joins must be exclusively to calls controlled by a common DCP.  I would prefer the former.

**Comment by benlangfeld** [comment]
Security zones added, but no recommendations around how to deal with app instance division with respect to joins. I'm not sure the spec is really the right place for this. I'm going to close this for now, but if anyone has any concerns, let me know.
