### ISSUE TITLE
Error type for "internal server error"

### ISSUE THREAD

**Issue by bklang** [rayo/xmpp#43]
In [section 6.2.1.1](http://ci.mojolingo.com/job/Rayo%20Spec/lastSuccessfulBuild/artifact/extensions/rayo.html#session-establishment-outbound-errors) we list several possible error conditions.  I suggest we add one for "the server encountered an internal error processing the request" as a catchall for some kind of server failing that is not protocol- or authorization-related.

**Comment by benlangfeld** [comment]
I would suggest we're covered by the core XMPP spec in this general case?

**Comment by bklang** [comment]
Is it worth mentioning this as a possible cause in the list of error causes? And specifying that existing XMPP errors are sufficient? I suggest this because we do this in other places.

**Comment by benlangfeld** [comment]
I would suggest mentioning that all standard XMPP errors may be used where one in the Rayo spec does not fit, but not mentioning any specific ones.
