### ISSUE TITLE
Hangup direction

### ISSUE THREAD

**Issue by lpradovera** [rayo/xmpp#45]
A way to determine which party has hung up a bridged call would be very useful for logging and tracking purposes.

**Comment by benlangfeld** [comment]
The client should know if they sent a `<hangup/>` or not. If they did not, they can assume the far end hung up. Rayo also does not link the lifecycle of joined calls, so it's really not a concern here.

Let me know if I've missed anything.

**Comment by bklang** [comment]
Is there a race condition where the client sends a hangup, but the server sees the far end hang up first?  Hangup direction is one of those odd things that is pretty useful.

**Comment by benlangfeld** [comment]
Your right. I guess we have to add this.
