### ISSUE TITLE
Mixers should be allocated by the server

### ISSUE THREAD

**Issue by benlangfeld** [rayo/xmpp#49]
Currently, it's not possible to ensure mixer name uniqueness both between and within security zones, but across instances of a client. If foo@bar.com/1 joins a call to mixer a@bar.com, then baz@bar.com/1 can also join calls it controls to a@bar.com. That's a security issue. Additionally, foo@bar.com/2 cannot, barring unspecified inter-client coordination, know that a@bar.com is created, let alone within its security zone (foo@bar.com).

The solution to this, as I see it, is to make mixers a server-allocated resource like calls, and require clients to request creation of a mixer much like requesting a new call using `<dial/>`. The server can then allocate a new mixer, return its JID as a response to the creation request, and advertise its presence to the bare JID of the requesting party. The server can then reject any attempts by parties in other security zones from joining calls to this mixer, or executing commands against it.

@loopingrage @bklang @mpermar Objections?

**Comment by loopingrage** [comment]
Seems complicated. You are truing to solve two problems here: uniqueness and security.

Why not just use a GUID on the client if you want uniqueness? That's basically what the client will do anyways. In Voxeo hosting, we concatenate the developer's account ID with the conference name like so: '16577|foo'. 16577 followed by a pipe character and the conference name of 'foo'. This is quite simple to do in your app if you have multiple tenants.

As for security, we use a similar approach on the server (i.e qualify the mixer-name with the base JID)

So if we get a command that looks like this:

``` xml
<iq type='set' to='ab0mr6@calls.rayo.org' from='coolapp@apps.rayo.org/foo'>
   <join mixer-name='1234' />
</iq>
```

It will get translated to:

``` xml
<iq type='set' to='ab0mr6@calls.rayo.org' from='coolapp@apps.rayo.org/foo'>
   <join mixer-name='coolapp@apps.rayo.org|1234' />
</iq>
```

Note that the mixer name now has the base JID as a prefix. This name-spacing approach is simple and and will enforce that mixers are scoped per app (i.e. JID)

Thoughts?

**Comment by benlangfeld** [comment]
So how does this work for mixer presence. You're saying that presence from 1234@mixers.rayo.org to a@example.com is something entirely different from presence sent to b@example.com, and that the mixer JID does not actually fully address the backend mixer? This is utterly abusing XMPP and makes me feel very uncomfortable. I would much rather simply scope mixers to a client JID on first join and return an error if another client tries to interact with that mixer. As for uniqueness, the spec can simply recommend that a UUID be used for mixers in order to avoid such collisions in real life.

**Comment by benlangfeld** [comment]
The other issue with implicit creation is that of addressing, similar to #41. Joining a mixer gives no indication of the full address the mixer will be found at once it's created. For this reason I now definitely favour the server-allocated mixer approach. Unless I get any objections, I'm gonna draft this tomorrow along with the ref changes.

**Comment by bklang** [comment]
One easy way to address this is consider a mixer domain a freestanding security zone.  Thus anyone who is allowed to create or join mixers on a given domain can join any mixer on that given domain.  Then, if you wanted to implement something higher level (like Tropo or Ameche) you could do so at that level, by concatenating developer IDs with the actual mixer name before requesting the resource from the mixer domain.

**Comment by benlangfeld** [comment]
That's not a general solution for all clients. How would Adhearsion deal with that, for example?

**Comment by bklang** [comment]
As Adhearsion is the Rayo client, and security should never be enforced in the client, it's moot about how Adhearsion would deal with it.  But if an Adhearsion application needed to segregate mixers into namespaces, it could do so using the concatenation method described earlier.

**Comment by benlangfeld** [comment]
Right, but you're suggesting that mixers be globally accessible, but you might have several ahn apps on a single rayo cluster and then your security is hosed. The concatenation method above for security is not acceptable due to its addressing abuse.

As I said, the addressing argument from #41 kills the entire thing in favour of server allocation, unless someone can come up with a proposal which addresses all three concerns:
- Security
- Addressing ambiguity
- Addressing identity (one address should mean one object, and should be global)

**Comment by bklang** [comment]
The mixers are globally accessible, but a mixer domain would be configured to only accept join requests from Rayo client JIDs in a specific calls domain. Thus having several Ahn apps is fine, as long as their domains are different.  The concatenation method is really only intended for application-specific issues, and is just a note of interest; it shouldn't be baked into the protocol at all.

**Comment by benlangfeld** [comment]
Using domains for security is a bad idea IMO because then you can't separate app1@jabber.org from app2@jabber.org. Unless you mean the server domain should be different, in which case then you've got even bigger problems and that's a huge implementation change.

**Comment by bklang** [comment]
Yes, you're right - I had not considered using a single domain where apps do not trust each other.  I don't really see another way around the issue then, server-generated mixers is probably best.

However, I'm not sure I'm satisfied with random, server-supplied mixer names as the only mechanism.  There is clear utility in an app developer being able to say "I want to join the 'sales' conference bridge", and not have to have the Rayo client (eg. Adhearsion) manage a mapping between logical names and allocated names.  And that doesn't even consider having multiple Adhearsion instances and the need to share such mappings.

**Comment by benlangfeld** [comment]
Except mixers are ephemeral, and there's no guarantee that someone else won't steal your mixer name while there's no-one in it.

**Comment by bklang** [comment]
Right, but for many, many applications, that's OK.  Hard-coded mixer names are the norm for most PBX-style applications.

**Comment by benlangfeld** [comment]
Right, but hard-coded mixer names won't work on a public cluster. The 'conference' mixer will be hugely contended. If we want nicely named mixers, we have to come up with an acceptable solution to the addressing identity issue, and the only one I can see is the application maintaining a mapping, perhaps combined with a name reservation (such that when a mixer is destroyed it does not become available for other client JIDs to create, though that pushes a big state burden onto the server).

**Comment by benlangfeld** [comment]
@loopingrage Your input on this issue would be appreciated in addition to the other issues we highlighted.

**Comment by benlangfeld** [comment]
Options:
1. Jose for simplicity, if XSF reject:
2. Ben K's suggestion
