### ISSUE TITLE
Receive a fax document

### ISSUE THREAD

**Issue by crienzo** [rayo/xmpp#72]
The proposed Rayo CPA spec https://github.com/rayo/rayo-server/wiki/CPA has a way to detect Fax CNG, but there is no way to tell the rayo server to actually receive the document.

The record component already has the function to receive audio and store it, would it make sense to just reuse that component and maybe put in an attribute that tells record we are recording a fax document?

**Comment by benlangfeld** [comment]
So, there's a lot of things in the record component currently focussed on audio such that I'd be uncomfortable repurposing it. I would suggest we should implement a new component for fax receipt. Sending a fax would be fairly simple using the existing output component and we can specify that if we have a use case.

I would suggest we go for something like this:

``` xml
<iq from='juliet@capulet.lit/balcony'
    to='9f00061@call.shakespeare.lit'
    type='set'
    id='h7ed2'>
  <receivefax xmlns='urn:xmpp:rayo:fax:1' t38="true"/>
</iq>

<presence from='9f00061@call.shakespeare.lit/eh3u28'
          to='juliet@capulet.lit/courtyard'
          type='unavailable'>
  <complete xmlns='urn:xmpp:rayo:ext:1'>
    <finish xmlns='urn:xmpp:rayo:ext:complete:1'/>
    <fax xmlns='urn:xmpp:rayo:fax:complete:1' uri='http://rayo.io/faxes/fax1.tiff' resolution='595x841' size='12287492817' pages='3'/>
  </complete>
</presence>
```

@crienzo I'd accept a pull request against the spec or can draft myself if you need it.

**Comment by dhauser** [comment]
I think it would make sense while looking at fax that we handle sending at the same time even though we don't have a current use case

**Comment by benlangfeld** [comment]
Can do, David. That'd probably look something like this:

``` xml
<iq from='juliet@capulet.lit/balcony'
    to='9f00061@call.shakespeare.lit'
    type='set'
    id='h7ed2'>
  <output xmlns='urn:xmpp:rayo:output:1' renderer='fax'>
    <document uri='http://example.com/fax.tiff'/>
  </output>
</iq>
```

**Comment by crienzo** [comment]
Yes, transmit of fax is a simple case.  

I don't think we should have a t38 param for receivefax.  The server should decide based on configuration how best to receive the fax, just like it does for everything else.

**Comment by crienzo** [comment]
I don't have time to update the spec for a couple of weeks since I'm finishing up another project.  If you guys can wait until then, I can do it.

**Comment by benlangfeld** [comment]
Spec is being built [here](http://ci.mojolingo.com/job/Rayo%20Spec/lastSuccessfulBuild/artifact/extensions/rayo-fax.html). Actual content on the way shortly.

**Comment by benlangfeld** [comment]
The spec should be more or less complete. @crienzo, please let me know what you think. If you agree with it, I'll implement the client-side stuff in Adhearsion/Punchblock and we can submit to the XSF once we have confirmed working integration.

**Comment by bklang** [comment]
I notice you include the resolution as a attribute of the `<fax/>` element, but are there other attributes that need including? Some possibilities:
- page size (letter vs. A4...I'm assuming this is transmitted, but may be implied by resolution)
- DPI (ditto above)
- fax station IDs
- transmission mode (thinking analog vs. t.38 here, but could also include the v.number)

Also, what happens in the event of a partial transmission or reception? Most real-world fax machines spit out whatever they received and indicate a transmission error of some kind.

**Comment by benlangfeld** [comment]
For reference, [the data FreeSWITCH provides](http://wiki.freeswitch.org/wiki/Mod_spandsp#Checking_the_results).

> - page size (letter vs. A4...I'm assuming this is transmitted, but may be implied by resolution)

`fax_image_size` might be this...

> - DPI (ditto above)

This can be calculated from a page size and the resolution.

> - fax station IDs

This is available in FreeSWITCH, but why would it be important to the app?

> - transmission mode (thinking analog vs. t.38 here, but could also include the v.number)

I don't think we get this. Why would it be important?

> Also, what happens in the event of a partial transmission or reception? Most real-world fax machines spit out whatever they received and indicate a transmission error of some kind.

We should implement some error conditions. Some available in FS are: http://wiki.freeswitch.org/wiki/Variable_fax_result_code. We might also want to page count `XofY` in cases of partial transmission.

**Comment by crienzo** [comment]
FS will fire events for each fax page received or transmitted and for the final report.  In addition, you can specify a starting/ending page to transmit and the fax ident and header.

The tx result event contains:
fax-document-transferred-pages
fax-document-total-pages
fax-image-resolution
fax-image-size
fax-bad-rows
fax-transfer-rate
fax-result-code
fax-result-text
fax-ecm-used
fax-local-station-id
fax-remote-station-id

The rx result event contains:
fax-document-transferred-pages
fax-document-total-pages
fax-image-resolution
fax-image-size
fax-bad-rows
fax-transfer-rate
fax-result-code
fax-result-text
fax-ecm-used
fax-local-station-id
fax-remote-station-id

**Comment by crienzo** [comment]
We report all sorts of SIP header info in offers, maybe we can package this report info up similarly?

**Comment by benlangfeld** [comment]
I think everyone is satisfied with the current spec and I'll submit it to the XSF for publishing today. They will take up to 2 weeks to publish it.
