### ISSUE TITLE
Rayo CPA: additional tones

### ISSUE THREAD

**Issue by crienzo** [rayo/xmpp#79]
Add busy and congestion tones?  These would be useful for dialer applications.

**Comment by benlangfeld** [comment]
I would expect these to be mapped to a Rayo `<end/>` event and not require CPA at all.

**Comment by crienzo** [comment]
Having worked on dialers, I can tell you this is not necessarily the case.   Many voip carriers are inconsistent in their completion codes and it is handy to detect the tones to improve call disposition.
