### ISSUE TITLE
call transfer?

### ISSUE THREAD

**Issue by crienzo** [rayo/xmpp#88]
Ben Klang noticed there is no way to initiate a SIP REFER.  Is this an oversight?

**Comment by benlangfeld** [comment]
It seems there isn't explicitly. I would expect `<redirect/>` to work before and after answer [in the way you describe](http://jira.freeswitch.org/browse/FS-6141?focusedCommentId=47647&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-47647) (302/REFER). I'm not sure there's a reason not to do this; any thoughts?

**Comment by crienzo** [comment]
It certainly would be simpler on the client side- you don't have to track state and can move the call at (almost) any time.

**Comment by bklang** [comment]
Looks good to me. :+1:

**Comment by crienzo** [comment]
redirect sent to a call under the control of another DCP results in conflict error, not "not-allowed".  Everything else is fine.

**Comment by benlangfeld** [comment]
Thanks for pointing that out, @crienzo. Fixed in 1230d86f70f73fbd953ad2571e40ae694b7363cc.
