### ISSUE TITLE
Pubsub: error when modifying multiple affiliations

### ISSUE THREAD

**Issue by tylorr** [rayo/xmpp#98]
When modifying multiple pubsub affiliations the [extension states](https://xmpp.org/extensions/xep-0060.html#owner-affiliations-multi):

> the service MUST return an IQ error (which SHOULD be <not-acceptable/>) with the invalid entries, where the affiliation returned is the original, un-altered affiliation

But the provided [example](https://xmpp.org/extensions/xep-0060.html#example-207) is not following this rule. It does not list which affiliation modifications are not acceptable.

**Comment by benlangfeld** [comment]
This is the wrong repository for these issues. This repository is for development of the Rayo suite of specifications. You are looking for github.com/xsf/xeps.
