### ISSUE TITLE
Pubsub: affiliation state change questions

### ISSUE THREAD

**Issue by tylorr** [rayo/xmpp#99]
In the [affiliations section](https://xmpp.org/extensions/xep-0060.html#affiliations) it talks about affiliation state changes and for a change from publisher to member is shows `n/a`.  What does that mean exactly? Does that mean a publisher cannot be changed to a member? Do they have to be changed to none first then to a member?

**Comment by benlangfeld** [comment]
This is the wrong repository for these issues. This repository is for development of the Rayo suite of specifications. You are looking for github.com/xsf/xeps.
